[build]
  # Use a CI-friendly build command that skips running the TypeScript project build
  # (some CI environments fail because of strict type errors).
  command = "npm ci && npm run build:netlify"
  publish = "dist"

[dev]
  command = "npm run dev"

[build.environment]
  # Use Node 20 to satisfy engine requirements for some dev dependencies
  NODE_VERSION = "20"
