[build]
  # Use a CI-friendly build command that skips running the TypeScript project build
  # (some CI environments fail because of strict type errors like unused imports).
  command = "npm ci && npm run build:netlify"
  publish = "dist"

[dev]
  command = "npm run dev"

[build.environment]
  # Optional: set Node version used by Netlify. Netlify will pick a default if omitted.
  NODE_VERSION = "18"
