## Netlify config at repository root
## Ensures Netlify uses the `frontend` subfolder as the build base

[build]
  # build inside the frontend folder
  base = "frontend"
  # install and build the Vite app
  command = "npm ci && npm run build"
  # publish directory relative to the base
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
