## Netlify config at repository root
## Ensures Netlify uses the `frontend` subfolder as the build base

[build]
  # build inside the frontend folder
  base = "frontend"
  # install and build the Vite app using the CI-friendly script
  command = "npm ci && npm run build:netlify"
  # publish directory relative to the base
  publish = "dist"

[build.environment]
  # Use Node 20 to satisfy newer dependency engine requirements
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
